name: Check New Branches

on:
  workflow_dispatch:

jobs:
  check_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Forked Repository
      uses: actions/checkout@v2
      with:
        repository: deepfence/vectorscan  # Use the 'org/repo' format

    - name: Fetch Latest Changes
      run: |
        git fetch origin
        git fetch --tags

    - name: List New Branches
      run: |
        git branch -r | grep -v ' -> ' | while read -r branch; do
          if ! git branch -a | grep -q "$branch"; then
            echo "New branch: $branch"
          fi
        done

    - name: List New Tags
      run: |
        git tag -l -n9 | grep -v '^{}$' | while read -r tag; do
          echo "New tag: $tag"
        done
