name: Check New Branches

on:
  workflow_dispatch:

jobs:
  check_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Forked Repository
      uses: actions/checkout@v2
      with:
        repository: deepfence/vectorscan  # Use the 'org/repo' format

    - name: Add Upstream Remote
      run: |
        git remote add upstream https://github.com/VectorCamp/vectorscan.git
        git fetch upstream

    - name: List New Branches
      run: |
        git fetch origin  # Fetch latest changes from the forked repository
        git fetch --all --prune  # Make sure to prune stale branches
        git branch -r | grep -v ' -> ' | while read -r branch; do
          if ! git branch -a | grep -q "$branch"; then
            echo "New branch: $branch"
          fi
        done
