name: Compare Forked Repository

on:
  workflow_dispatch:

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Forked Repository
      uses: actions/checkout@v2
      with:
        repository: deepfence/vectorscan  # Use the 'org/repo' format

    - name: Add Upstream Remote
      run: |
        git remote add upstream https://github.com/VectorCamp/vectorscan.git
        git fetch upstream

    - name: Compare Branches
      run: |
        git fetch origin  # Fetch latest changes from the forked repository
        git checkout main  # Replace 'main' with the branch you want to compare
        git diff origin/main upstream/main  # Compare branches
